### ISSUE TITLE
Everything produces a error and fails

### ISSUE THREAD

**Issue by TomJB1** [Josee9988/MinifyAllCli#85]
# **🐞 Bug Report**

## **Describe the bug**
When I try to do anything (including --version or --help) it produces a error:

https://gist.github.com/TomJB1/f97bf18123b9836542d30cf11a4a9b71

---

### **Is this a regression?**
I don't know

---

### **To Reproduce**

1. Instal using the command `npm i -g @josee9988/minifyall`
2. Run `minifyall --version`, `minifyall --help` or `minifyall --dir exampleDir/`

---

### **Expected behaviour**
* Display the help page/version or to minify the files in the directory specified!

---

### **Media prove**

---

### **Your environment**

* OS:  Debian GNU/Linux 12 (bookworm) x86_64
* Node version: v22.7.0
* Npm version: 10.8.2
* Browser name and version: Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0

---

### **Additional context**

*

**Comment by TomJB1** [comment]
It seems to be working on my other computer (Windows) so this might be a issue on my end.

**Comment by Tasselmi** [comment]
me too on my macbook with apple m2 chip

```shell
==r&&Pc.init(r),void 0!==t&&Yc.from(e,t),_h(bc,e),eh(e)||Nh(I),nf&&Ih(Ko),i=e,n=ah(i,(function(e){if(Jo(e,"request"),""===e)throw new Ch("request",e,"must be a non-empty string");var t=Eu(e,i),r=Pc.state.package.default,n=ge(t);Yc.get(n)===r&&Yc.set(n,r.clone());var s=_c(e,i),a=s.module.exports;return 1!==s.type&&R.bridged.set(a,s),a}),(function(e,t){return Eu(e,i,!1,t)})),n.main=Pc.state.module.mainModule,n}):(Jh=R,Jh.inited=!0,Jh.reloaded=!1,Yn.enable(af),Oh.enable(af),Yn.enable(of),Oh.enable(of),Xh?Yh(Ta):Zh||rf?(_h(bc),Nh(I),Yh(Ta)):(Qh||ef||ch())&&(_h(En),(function(e){"use strict";fh.manage(e,"runMain",(function(t,r,i){var n=I.argv,s=n[1],a=Eu(s,null,!0),o=Yc.from(a),u=fh.find(e,"runMain",dh(o.range));return null===u?Reflect.apply(r,this,i):Reflect.apply(u,this,[t,r,i])})),fh.wrap(e,"runMain",(function(){var e,t=I.argv,r=t[1],i=Eu(r,null,!0),n=Pc.state.package.default,s=ge(i);Yc.get(s)===n&&Yc.set(s,n.clone());try{_c(r,null,!0)}catch(e){throw!n.options.debug&&is(e)?ds(e,{filename:i}):fs(e),e}e=O(I,"_tickCallback"),"function"==typeof e&&Reflect.apply(e,I,[])})),bc.runMain=e.runMain})(En),Nh(I)),ef&&(function(e){"use strict";e.console=xo.console.module.exports,e.process=xo.process.module.exports})(of),tf&&nf&&Ih(Ko)),n.default=Jh})]).default;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

TypeError: Function.prototype.apply was called on undefined, which is a undefined and not a function
    at $o (/opt/homebrew/lib/node_modules/@josee9988/minifyall/node_modules/esm/esm.js:1:224377)
    at wu (/opt/homebrew/lib/node_modules/@josee9988/minifyall/node_modules/esm/esm.js:1:227324)
    at Eu (/opt/homebrew/lib/node_modules/@josee9988/minifyall/node_modules/esm/esm.js:1:227999)
    at Module.<anonymous> (/opt/homebrew/lib/node_modules/@josee9988/minifyall/node_modules/esm/esm.js:1:295976)
    at n (/opt/homebrew/lib/node_modules/@josee9988/minifyall/node_modules/esm/esm.js:1:279589)
    at Object.<anonymous> (/opt/homebrew/lib/node_modules/@josee9988/minifyall/bin/minifyall.js:19:1)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
    at Module.load (node:internal/modules/cjs/loader:1317:32)
    at Module._load (node:internal/modules/cjs/loader:1127:12)

Node.js v22.6.0
```
